name: stride
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  flutter_bloc: ^9.1.0
  firebase_auth: ^5.5.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true


  assets:
     - assets/auth_social_logo/google_logo.png